### ISSUE TITLE
Inicio: Problema con margenes laterales w@414-530px

### ISSUE THREAD

**Issue by AlvaroArriagada** [Ensambler/emblr-official-site#1]
Se detectan problemas en la resolución entre los 414px y los 530px. Se pierden margenes laterales en la vista home.

**Comment by diegoulloao** [comment]
Visto. Lo vamos a corregir!

**Comment by AlvaroArriagada** [comment]
Okay. El 31-05-2019 10:55, Diego Ulloa <notifications@github.com> escribió:Visto. Lo vamos a corregir!

**Comment by AlvaroArriagada** [comment]
Solucionado. Puse un padding: 0 35px !important; en la linea 2951 del style.css .

Otra solución era quitar el .row { padding: 0px 0px } pero como .row es utilizado en otras secciones podía afectar. TODO OK.
