### ISSUE TITLE
Inicio (detalle): "Ing de software para ..." debiese achicarse en w@768px

### ISSUE THREAD

**Issue by diegoulloao** [Ensambler/emblr-official-site#10]
Se produce una descompensación entre el tamaño del logo (que se achica) y el tamaño del título "Ingeniería de Software para Soluciones Empresariales Integradas" que se mantiene.

Debiese haber armonía.

**Comment by AlvaroArriagada** [comment]
Solucionado, se achico el tengo h3 de 2.6rem a 2.4rem para la media query 768px.
