### ISSUE TITLE
Inicio (detalle): Botones "sobre nosotros" y "nuestros servicios" debiesen achicarse en w@400-560px

### ISSUE THREAD

**Issue by diegoulloao** [Ensambler/emblr-official-site#11]
Botones en modo smartphone se ven demasiado grandes en comparación al tamaño de letras, logo y espacio disponible.

Ver en conjunto del asesoramiento de @paulpopaul.

**Comment by AlvaroArriagada** [comment]
Como opinión personal, encuentro que no es grande para todos los smartphone, si no que para aquellos que están en una resolución bajo los 400px. 

Agregué las siguientes lineas para esa media query:
  .home-content__button .btn {
    height: 5.5rem !important;
    max-width: 28rem;
    font-size: 10px;
  }

De esta forma reduje la fuente en 10px, el alto del boton en 0.5 rem, y el largo del boton en 4rem. 

En espera a aprobación de @paulpopaul

**Comment by paulpopaul** [comment]
@AlvaroArriagada modifique el max-width: 28rem; a max-width: 24rem; es más pequeño pero hace un mejor equilibrio con los elementos 

agregue a la query de 500px las mismas propiedades (max-width: 24rem;) ya que con 28rem quedaba ancho aun.
