### ISSUE TITLE
Inicio: Contenedor adquiere demasiado height en w@1400-1600px y h@<900px

### ISSUE THREAD

**Issue by diegoulloao** [Ensambler/emblr-official-site#14]
No sé si este issue tiene relación con el mismo issue publicado anteriormente en https://github.com/Ensambler/emblr-official-site/issues/9

Puede deberse nuevamente a un problema de las media-query agregadas ayer para este efecto y la ctm. Jajaja inicio ql wn ...

**Comment by AlvaroArriagada** [comment]
Es el mismo issues creo.

**Comment by diegoulloao** [comment]
Si es el mismo da por cerrado este tema no más ;)
