### ISSUE TITLE
Apartado-1: Espacio entre texto h6 y botón se excede en w@560-640px

### ISSUE THREAD

**Issue by diegoulloao** [Ensambler/emblr-official-site#18]
El espacio entre el texto "Tenemos las mejores herramientas del mercado a tu disposición" y el botón "Contáctanos" es diferente al superior de este mismo botón.

* Por lo visto el problema aparece por no ocultar el texto excedente (nueva línea resultado del efecto shuffle letters que tiene).

* Se debiese definir tal vez un height adecuado para ocultarlo (overflow:hidden).

**Comment by AlvaroArriagada** [comment]
Enviar pantallazo de la observación, no se entiende "es diferente al superior de este mismo botón".

**Comment by diegoulloao** [comment]
![Captura de Pantalla 2019-06-07 a la(s) 15 04 44](https://user-images.githubusercontent.com/45423661/59127490-c6050300-8935-11e9-9d0d-6935ea118e0d.png)

w@565px de referencia en la captura.

**Comment by diegoulloao** [comment]
SOLUCIONADO.

Se saca height: 60px de @media max-w@640px style.css:4976.
Se agrega @media max-w@561px style.css:4987 con:

```
@media only screen and (max-width: 561px) {
  .section-page.apartado-1 > h6 {
    height: 60px;
  }
}
```
