### ISSUE TITLE
Noticias: Al pinchar flechas éstas se marcan con cuadro celeste.

### ISSUE THREAD

**Issue by diegoulloao** [Ensambler/emblr-official-site#22]
@AlvaroArriagada, probablemente haya que hacerles lo mismo que a lo de los contenedores de cada historia, pls.

**Comment by diegoulloao** [comment]
Estaba solucionado.

**Comment by AlvaroArriagada** [comment]
Olvidé escribir... se solucionaba en la linea: 4086 aprox, donde había un outline-width, dicho valor había que cambiar por 0px para que al presionar no marque el borde color azul que viene por defecto. 
outline-width: 0px;
Commit: 137f628457f8842032925a643b72ff16ba5dad68
