### ISSUE TITLE
Inicio: Problema lupa y hand cursor al medio del lente (búsqueda).

### ISSUE THREAD

**Issue by diegoulloao** [Ensambler/emblr-official-site#23]
Al poner mouse al centro de la lupa desaparece mouse mano para abrir campo de búsqueda.

**Comment by AlvaroArriagada** [comment]
Solucionado, la x estaba casi al centro de la lupa, eso hacía el cursos desapareciera, solucionó centrando el div de la x, además agregando el cursos: pointer.

**Comment by AlvaroArriagada** [comment]
Commit: 137f628457f8842032925a643b72ff16ba5dad68

**Comment by diegoulloao** [comment]
La solución originó que se desplazara la x de cerrar al abrir el campo de búsqueda!

**Comment by diegoulloao** [comment]
Problema de x de cerrar solucionada -> 31fa209
