### ISSUE TITLE
Noticias: Flecha derecha historia muy se pega a .page-dots en w@1024-1200px

### ISSUE THREAD

**Issue by diegoulloao** [Ensambler/emblr-official-site#24]
La flecha derecha del slider de las historias se muestra demasiado pegado a los .page-dots en resoluciones que van desde los 1024px a los 1200px.

**Comment by AlvaroArriagada** [comment]
Solucionado, se reduce los pixeles a ambos lados en dichas resoluciones por left: -25px; y right: -25px; linea :4408 aprox de style.css

**Comment by AlvaroArriagada** [comment]
commit: 4ac47a9e4e7c3923674baa141f304686f490934d

**Comment by diegoulloao** [comment]
Encuentro que la maquetación entre ese rango no es la apropiada al invadir el márgen que se respeta en todas las demás secciones.

**Comment by diegoulloao** [comment]
Solucionado. Se hacen arreglos desde > w@1024px en 45bc2d1
