### ISSUE TITLE
Inicio: Problema margen inferior w@1400-1360px, h@800px

### ISSUE THREAD

**Issue by diegoulloao** [Ensambler/emblr-official-site#3]
Margen inferior desaparece en las medidas especificadas, resultado de que se reduce el height total de la sección.

**Comment by diegoulloao** [comment]
@AlvaroArriagada esto fue lo que solucionamos?

**Comment by AlvaroArriagada** [comment]
Se solucionó problema, agregando doble condición a una media query, desde mín width: 1366px y max height: 940px se aumenta el tamaño del min-heigth a 900px.
