### ISSUE TITLE
Noticias: Al hacer click en una noticia se marca un cuadro naranjo (a veces azul) en su contenedor.

### ISSUE THREAD

**Issue by diegoulloao** [Ensambler/emblr-official-site#7]
Al parecer el culpable es el plugin slick que marca los contenedores de cada historia al hacer click. Buscar la forma de eliminarlo vía css.

**Comment by AlvaroArriagada** [comment]
Solucionado: Agregando un outline-width: 0px; en la linea 4060 del style.css en la clase .stories-container{}
