### ISSUE TITLE
Inicio: Se alarga demasiado contenedor de home en w@1366-1600px y h@>900px

### ISSUE THREAD

**Issue by diegoulloao** [Ensambler/emblr-official-site#9]
Por alguna razón el contenedor de home (creo .s-home) se está alargando demasiados cuando la resolución es width entre 1366 y 1600px y height mayor a 900px.

* Puede deberse a agregaciones en media-query que hicimos ayer respecto a esto. Alguna condición relacionada con height podría estar al revés (ejemplo que sea min-height en vez de max-height o viceversa).

@AlvaroArriagada.

**Comment by AlvaroArriagada** [comment]
Height mayor a 900px? Nunca definimos esa reso... :O

**Comment by AlvaroArriagada** [comment]
Solucionado, había un /* .s-home{
    height: 120vh;
  }*/ 
Puesto, que generaba ese espacio, sin embargo, las reglas están solo para 1366px hacia arriba, no están todas las resoluciones existentes... (Bajo 1366px sobre 900px no hay reglas como aquellas).

**Comment by AlvaroArriagada** [comment]
commit: e3ecab1cf361bf5b85d7b0c27d00c0b44144f4f9
